### ISSUE TITLE
Blank Page

### ISSUE THREAD

**Issue by moffzar7** [aifaiz/ipay88-woocommerce#1]
Hi, I have tested the plugin and all went well until it redirect back to the page template which it gives customer blank page. How do we fix that?

**Comment by aifaiz** [comment]
i think its because it didnt process properly after returned from the reponse. maybe we can try adding a wp hook on init to always wait for response. let me see what can be done and make a commit

**Comment by aifaiz** [comment]
i had pushed a commit. try see if everything is working

**Comment by moffzar7** [comment]
Hi,

Thank you. I will check it and get back to you shortly.

**Comment by moffzar7** [comment]
Hi, I got message

"somethings wrong with the response"

**Comment by moffzar7** [comment]
Hi,

Any update? Previously the plugin can go through payment gateway but the
latest update gave "somethings wrong with the response" without even going
to payment gateway.

Thanks.

**Comment by aifaiz** [comment]
i had just pushed a new commit. try see if the problem still persist

**Comment by moffzar7** [comment]
Hi, I have just tested it. But this time I got "payment failed." message...

**Comment by markfive-proto** [comment]
i think u can actually set the msg/content u want into the payment failed session as an alternative. 
I've tested the wp_redirect('checkout') it doesn't work so I just inserted a hyperlink tag at the payment failed message. btw nice work aifaiz!

**Comment by markfive-proto** [comment]
@moffzar7  it appears u have to check the "create new account" options in checkout page for you to successfully proceed to the ipay88 page. Try to if this is the issue u're having

**Comment by aifaiz** [comment]
i had ammend another fix. try if this solve the issue. 
sorry for the delay! ive been totally busy. haha

**Comment by aifaiz** [comment]
alright. seems like the issue has been resolved with the latest commit.
