### ISSUE TITLE
Cannot proceed to the ipay88 payment page

### ISSUE THREAD

**Issue by khairisuleiman** [aifaiz/ipay88-woocommerce#10]
Assalamualaikum Mr. AIfaiz,

Really need your assist to help me on the ipay88 payment page. Its prompt a non secure form and not redirect to the ipay88 payment page. Below link are the screenshot on the page. Really appreciate your help. Thanks.
https://gyazo.com/092951ab4c1b5f84c12bfab27e706b1d
https://gyazo.com/8a00a60804add4ac191f018eedd7d984

**Comment by shenleng** [comment]
Hi,

I faced the same problem too. It is not direct to ipay88 payment page.

**Comment by aifaiz** [comment]
hi. try see if your javascript or theme has some error. this plugin requires the wordpress style `jQuery` to run properly. 

see this link [jquery on footer](https://github.com/aifaiz/ipay88-woocommerce/blob/master/aics-ipay-gateway.php#L76) which is running on the footer of the template.

**Comment by junsenlim** [comment]
Hi, aifaiz. I just downloaded the wordpress plugin AiCS ipay88 Woocommerce. Waiting for it to work and I eventually cannot open my website. It continued to appear this line: 
Fatal error: Class 'WC_Payment_Gateway' not found in /home2/waguuo0aeeq4/public_html/wp-content/plugins/aics-ipay88-woocommerce/libs/faiz-gateway-class.php on line 10

I try to reinstall the wordpress file in public_html, but the problem remain the same. How can I fix it? I just want my website back. Please help, thank you very much.

**Comment by aifaiz** [comment]
this plugin need woocommerce to work. u need to install woocommerce first.
try deleting the folder on wp-plugin and refresh your site.

**Comment by junsenlim** [comment]
I deleted the folder already but the problem still remain. I can't open my
site and continue to see this line:

*Fatal error*: Class 'WC_Payment_Gateway' not found in
*/home2/waguuo0aeeq4/public_html/wp-content/plugins/aics-ipay88-woocommerce/libs/faiz-gateway-class.php*
 on line *10*

FYI, my website name is moomoobf.com. But the line above appears to be
*waguuo0aeeq4.
*I wonder is this really matter to the problem? Please help, TQ ya.

*Moo Moo Balloon & Flower*
No. 42A, Lot 21, Jalan Indah 2/1
Taman Indah 2 Pekan Sekinchan
45400 Sekinchan, Selangor
*Tel: 018-2418 888 *

**Comment by aifaiz** [comment]
that means you still havent deleted the plugin folder.
delete it on `public_html/wp-content/plugins/aics-ipay88-woocommerce` folder.
.
or try to learn how wordpress handle their plugins first.
.
be sure to install `woocommerce` plugin first before installing this plugin to avoid this error in the future
.
btw. im not sure about your `waguuo0aeeq4` it seems to me that it was not part of my plugin.

**Comment by junsenlim** [comment]
Hi. It happened to be I am checking the other site file. I deleted the file
in the correct site which encounter the problem then everything goes well.
Thanks for your help aifaiz. I am quite new to these things, so it takes
time for me to understand how it actually works.

*Moo Moo Balloon & Flower*
No. 42A, Lot 21, Jalan Indah 2/1
Taman Indah 2 Pekan Sekinchan
45400 Sekinchan, Selangor
*Tel: 018-2418 888 *
