### ISSUE TITLE
the testing transaction was succeed but your side do not implement backend URL

### ISSUE THREAD

**Issue by AbhinayMe** [aifaiz/ipay88-woocommerce#11]
> Based on the checking, the testing transaction was succeed but your side do not implement backend URL.
> 
> For your information, Backend URL is a page at merchant server that act as secondary URL to receive SUCCESS payment status from ipay88 in case the Response URL fail to get notification. Below are the possibility of Response URL fail to get notification:
> 
> Internet connection timeout/not stable on customer device thus iPay88 not able to return payment status to merchant response page after payment.
> 
> Customer accidentally close web browser before payment cycle complete
> 
> Customer device hang after the payment is processed thus iPay88 not able to return payment status to merchant response page.
> 
> Bank delay response to ipay88 payment gateway.
> Henceforth, we would encourage you to implement backend post/backend URL into your system which should able to reduce the mention issue.
> 
> A correct backend url implementation should return with Response Code "200" and Response Data "Receive OK".
> Do revert back to us once you fix the issue and do a success RM1 testing again

That was the message from ipay88. Please assist how to.  Is this from your side or from WooCommerce ?

**Comment by chinnuabhi** [comment]
`<input type="hidden" name="ResponseURL" value="http://P*******s.com/payment/">\n`

I just found this. Does this mean that I'm doing something wrong with permalinks?

**Comment by aifaiz** [comment]
hi. sorry for the late reply. this feature havent yet to be implemented. ill push to `master` when its done. 
thank you for using this plugin and your feedback

**Comment by saonkhan** [comment]
Hi SOrry for entering here, i was looking for the same solution after the test transaction, The ipay88 agent said this same happened with my website and for this reason still i am not able to activate account for user.
Can you please help me like how i can solve this matter step by step.
Thanks in advance

**Comment by lordlaw** [comment]
Hi, 

am having the same issue.
see if any other idea to do it ?

**Comment by aifaiz** [comment]
Hey guys. i havent got time to manage the plugin. Thank you for pointing out that this plugin requires the `Backend` feature. i have emplemeted it. try it first. let me know if its working. (i will send an update to the plugin on wordpress soon. or right now)
