### ISSUE TITLE
Invalid Parameter (UserName)

### ISSUE THREAD

**Issue by JakeCube** [aifaiz/ipay88-woocommerce#12]
Recently i installed this plugin, i also requested a Demo account from ipay88.
When i proceed the payment it receive invalid Invalid Parameter (UserName)...
As studying the code, notice that Username is set by:

`<input type="hidden" name="UserName" value="<?php echo $current_user->user_firstname.' '.$current_user->user_user_lastname; ?>">`

If i'm not mistaken understanding this, the UserName will combining First Name and Last name at checkout page. But it seems failed to get the value.

1. Is the last name "user_user_lastname" mean to be like that?

2. May i know where is the "current_user->user_firstname.' '.$current_user->user_user_lastname;" collect from? 
I will try to debug with this...
(Is this feature only support logged in user to check out? Not supporting guest check out?)

3. Do you able to provide solution for this? If available,  I would like to buy few hour from you that help me solve this issue. Thank You

**Comment by aifaiz** [comment]
hey @JakeCube  thanks for reachin out. The `user_firstname` and `user_lastname` are called based on the `current user` who is logged in. i had amended the plugin to work both ways which is from `$order` data and also from `$current_user` data. See the referenced commit for the code. 

regarding your 3rd question, feel free to make a donation [here](https://hamizulfaiz.com/donate/plugin/ipay88/woocommerce) for my coffee. haha

Regards,
FAiZ

**Comment by JakeCube** [comment]
Does it will able working with Guest check-out? 

Btw i notice the code showed is  `$current_user->user_user_lastname` with double "user" is this normal?

**Comment by aifaiz** [comment]
I am not sure with Guest check-out myself. but the plugin will handle the `$user` data with `$order` if the `$current_user` are not set. which could be assumed to work with Guest checkout

`$current_user->user_user_lastname` is wrong. im not sure which version is that. Current version had changed to use a variable called `$user_fullname`. which derrived from the explaination above

**Comment by JakeCube** [comment]
May i have the URL for latest plugin download? Thanks for swift respond!

**Comment by aifaiz** [comment]
you can update from the wordpress plugin page. just go to your admin and click update to new version. I have updated the wordpress.org plugin repo too

may you have a happy days ahead!
thank you for using this plugin @JakeCube

**Comment by JakeCube** [comment]
@aifaiz I noticed the plugin update about 20min ago, but i don't see  update button for the plugin

**Comment by aifaiz** [comment]
are you still able to update?

you can also try these options:

1. Uninstalling the plugin and reinstall it.
2. Download from this repo and upload to your site using FTP
