### ISSUE TITLE
plugin install crashed

### ISSUE THREAD

**Issue by fivaxisdigital** [aifaiz/ipay88-woocommerce#13]
Salam bro,
Website wordpress terus crash lepas activate plugin ipay88

please review. tq

**Comment by aifaiz** [comment]
hi, terima kasih guna plugin ni. boleh beri detail crash? atau `error_log`. lebih membantu untuk cari bug. 

tq

**Comment by fivaxisdigital** [comment]
website terus tak boleh buka

**Comment by aifaiz** [comment]
delete plugin. cari file `error_log` dari `public_html` dan post disini utk rujukan. sy akan debug

**Comment by fivaxisdigital** [comment]
[07-Aug-2018 08:17:37 UTC] PHP Fatal error:  Call to a member function getResponse() on null in /home/fuyyoh/public_html/wp-content/plugins/ipay88-woocommerce-master/aics-ipay-gateway.php on line 83

**Comment by aifaiz** [comment]
boleh cuba re-download plugin. error fixed.
refer commit `16530f807f677059d644210dcec19ce2e25eb018`

**Comment by fivaxisdigital** [comment]
ok noted. tq sir

**Comment by aifaiz** [comment]
no problem

**Comment by fivaxisdigital** [comment]
its working now. awesome plugin !

**Comment by aifaiz** [comment]
thanks bro!
