### ISSUE TITLE
message kat web page RECEIVEOK.

### ISSUE THREAD

**Issue by btlim05** [aifaiz/ipay88-woocommerce#17]
Bro. terima kasih atas ipay88 anda. Sekarang ini bila saya guna plugin ini, saya terima url ini selepas payment https://webextend.com.my/payment dan message kat web page RECEIVEOK. Mengapa yar? saya ingat the message akan tunjuk Thank you and Receipt

**Comment by aifaiz** [comment]
hi bro. sori lambat reply. lama tak tengok repo ni. boleh refer di `pull request` #15 . download latest plugin dari github n reinstall plugin. see if it works

**Comment by btlim05** [comment]
thank you for your reply bro.

________________________________
