### ISSUE TITLE
Response data only return RECEIVEOK (ipay88)

### ISSUE THREAD

**Issue by jryz101** [aifaiz/ipay88-woocommerce#18]
Hi aifaiz, I was using this ipay88 woo-commerce plugin for my woo-commerce store. The issue I have was after enable the backend URL, woo-commerce is not sending order email to customer after the transaction has been made.

I asked ipay88 support and they reply: Please ensure that Response Data only return RECEIVEOK to ipay88 server without any HTML code.(check screenshot).

Can you let me know how do I fix this?

![Screen Shot 2019-11-04 at 6 17 32 PM](https://user-images.githubusercontent.com/23055114/68114075-270a2480-ff30-11e9-9937-c0d8c65e7cfe.png)

​

**Comment by aifaiz** [comment]
hey man, sorry for the late response. ill get into this

**Comment by jryz101** [comment]
Hey aifaiz. Thanks for the response. Do let me know when you have done the fixing. Appreciate it.✌🏻

**Comment by aifaiz** [comment]
hey man. ive added a fix and improvement to the backend response. i am so so sorry for the long delay. i am currently having too much task at hand. 

and thank you for using this plugin!

**Comment by jryz101** [comment]
Hey man. Thanks for the effort. Great job!

**Comment by Raton001** [comment]
I am facing the same problem in laravel now. 
Could You plz help me?

 public function backend_response(Request $request){
    // dd($request->ErrDesc);
    $Merchant_Code = env('Merchant_Code');
    $Merchant_Key =  env('Merchant_Key');
    // $source =  $Merchant_Key.$Merchant_Code."B00000001100MYR";
    // $signature = sha1($source);

    $decode =urldecode($request);
    $merchantcode = $request->MerchantCode;
    $paymentid = $request->PaymentId;
    $refno = $request->RefNo;
    $amount = $request->Amount;
    $ecurrency = $request->Currency;
    $remark = $request->Remark;
    $transid = $request->TransId;
    $authcode = $request->AuthCode;
    $estatus = $request->Status;
    $errdesc = $request->ErrDesc;
    $esignature = $request->Signature;
    $ccname = $request->CCName;
    $ccno = $request->CCNo;
    $s_bankname = $request->S_bankname;
    $s_country = $request->S_country;

    $source =  $Merchant_Key.$merchantcode.$paymentid.$refno."100".$ecurrency.$estatus;
    // $signature = sha1($source);
    $mySignature =  hash('sha256', $source);
    // $signature_decode =  urldecode($estatus);
    
    try {
      DB::beginTransaction();
      if($mySignature==$esignature){
        if ( $estatus ==1 ){

            DB::table('donates')->where("refno",$refno)->whereNull('estatus',null)->update([
              "merchantcode"=>$merchantcode,
              "paymentid" => $paymentid,
              "refno" =>$refno,
              "amount" => $amount,
              "ecurrency" => $ecurrency,
              "remark" => 'Success',
              "transid" => $transid,
              "authcode" => $authcode,
              "estatus" => $estatus,
              "errdesc" => $errdesc,
              "signature" => $esignature,
              "ccname" => $ccname,
              "ccno" => $ccno,
              "s_bankname" => $s_bankname,
              "s_country" => $s_country,
              "url" => $request->path(),

            ]);
            //return response()->json(['RECEIVEOK' => 'RECEIVEOK'], 200);            
            return response('RECEIVEOK', 200)->header('Content-type: application/json');


Route 

Route::post('backend_response', 'DonateController@backend_response')->name('backend_response');
Route::get ('/backend_response', function(){
        // return "RECEIVEOK";
        // return response('RECEIVEOK', 200)->header('Content-Type', 'application/json');
        echo strip_tags("RECEIVEOK",ENT_QUOTES);
});

**Comment by aifaiz** [comment]
hey @Raton001 `Laravel` way of returning a response is different from `Wordpress`. they handle it differently.
