### ISSUE TITLE
Hi, having issue with {domain}/payment/?backendipay=1

### ISSUE THREAD

**Issue by nemadaliev** [aifaiz/ipay88-woocommerce#19]
Hi, 
Having issue with {domain}/payment/?backendipay=1. Rest are fine.
iPay88 saying coz of it, having transation validation error. 
They say need to call {domain}/?backendipay=1

How and where can fix it? 
Thank you.

**Comment by nemadaliev** [comment]
Thanks, i think after updating the plugin, all are fine. keep good work.

**Comment by aifaiz** [comment]
hey @nemadaliev !

sorry for the late reply. Glad that worked out for you. Feel free to reopen this issue if the problem persist. ill take a look. 

Regards,
FAiZ
