### ISSUE TITLE
this should be great!

### ISSUE THREAD

**Issue by landhell** [aifaiz/ipay88-woocommerce#2]
hi, this plugin should be great especially for Malaysian WP and WooCommerce users. however, i seem unable to make it works.

after setup, i try a test order by clicking the "Place Order", i saw the URL bar directed to mobile88.com in first place, then a dialog box stated "non secure form", then i click "send", then it redirected back to my site and stuck on the "payment" page template and displaying "Processing, Please wait while we redirect you to the payment site.", i have no idea what shall i do next, could you please assist, thank you!

**Comment by ejat** [comment]
I have the same issue as the user above. Appreciate if you could assist us. Thanks!

**Comment by aifaiz** [comment]
hi everyone, thanks for reaching out!

I had pushed another latest commit to the master branch. see if this solved your issues.

I diagnose the response code which is here 

[faiz-gateway-class.php line198](https://github.com/aifaiz/ipay88-woocommerce/blob/master/libs/faiz-gateway-class.php#L198)

i had added additional code like this:

```
elseif($status != 1 && $signed == $ret_sign):
    $order = new WC_Order( $refno );
    $order->update_status('failed', __( 'Failed', 'woocommerce' ));
    wp_redirect($this->get_return_url( $order ));
   exit;

```

a bit of explaination:
`the response from ipay88 failed and there is no condition to handle "failed payment". so i made another condition on the response code.`

hope this solved your isue!

try uninstalling the plugin and download the latest from the master branch
