### ISSUE TITLE
Issue with WordPress Version 5.4.1

### ISSUE THREAD

**Issue by Japheth77** [aifaiz/ipay88-woocommerce#23]
Hi Aifaiz,

We're a nonprofit organization and we have impacted **300+** underprivileged lives of children in Malaysia. 

However, we facing an issue on the plugin AiCS ipay88 Woocommerce version **1.4.0** is not compactable with the current version of the WordPress **5.4.1**. 

Please resolve the issue as soon as possible. 

Best Regards,
John

**Comment by aifaiz** [comment]
Hi, thanks for using my plugin. 

i will need more information from your end. did you use `Woocommerce`? 
if you are using woocommerce, this plugin will work just fine even though its not yet updated.

Regards.
AiFAiZ

**Comment by aifaiz** [comment]
ill close this since no response
