### ISSUE TITLE
Failed payment

### ISSUE THREAD

**Issue by braderdesign** [aifaiz/ipay88-woocommerce#25]
Hi, I am having a problem using your plugin which whenever I tried to make a payment, it ended up as failed with this kind of message 'Unfortunately your order cannot be processed as the originating bank/merchant has declined your transaction. Please attempt your purchase again.' I am using woocommerce on my site. 

Any suggestion?

**Comment by aifaiz** [comment]
logically it should work out of the box. if you keep getting failed status, see if your site is using SSL or not. cz ipay88 is using SSL and doing the "redirect" from their end form SSL to non-SSL site will be always failed.

**Comment by braderdesign** [comment]
I'm not using SSL as this is a subdomain before I move to the main domain. That would seem to be the problem then, thank you for your help. I will try again once I migrate it to the main domain.
