### ISSUE TITLE
validateipay88.faiz’s server IP address could not be found.

### ISSUE THREAD

**Issue by henryjhg** [aifaiz/ipay88-woocommerce#28]
Hi,
I keep getting this error when I try to test the payment gateway (Redirected from Payment page). Is there something I missed out on?

* Payment Gateway is in test mode
* Checkout price is exactly RM1.00
* Merchant ID and Key already configured.

Thank you.
![Screenshot 2020-09-15 at 10 57 55](https://user-images.githubusercontent.com/4067376/93160200-6d303700-f742-11ea-9839-5843e108f843.png)

**Comment by etsen** [comment]
Change to live mode instead of test mode

**Comment by henryjhg** [comment]
> Change to live mode instead of test mode

Yes, it worked when I switched to live mode. Thought I could test the payment process first.
I'll close this case now.

**Comment by aifaiz** [comment]
ah, my bad there, ive been doing my local testing for the backend response and put a local url to the testing. ill remove this code on the next version.

**Comment by henryjhg** [comment]
> ah, my bad there, ive been doing my local testing for the backend response and put a local url to the testing. ill remove this code on the next version.

Yeah I thought the url in [faiz-driver.php](https://github.com/aifaiz/ipay88-woocommerce/blob/master/libs/faiz-driver.php) file looked off. Thanks for the heads up.
