### ISSUE TITLE
Cant send woocommerce automated emails when plugin is activated

### ISSUE THREAD

**Issue by etsen** [aifaiz/ipay88-woocommerce#29]
Hi, thanks for the great plugin. However when this plugin is activated with woocommerce, the emails are not sent out (all email except Failed order email). Tried mail logging but no logs found. Tried fixing SMTP but doesn't work. Then checked all plugins, all works well and email are sent out, only when AICS ipay88 plugin, emails are not sent. When I tested email (with some other automate woocommerce email plugin), it shows 'call to a member function "get_email()" on null'.

**Comment by aifaiz** [comment]
Hi @etsen 

Unfortunately i cant help you with that. because this plugin will not send emails and the order emails are handled by `Woocommerce`. this plugin will only do `payment processing`

you might want to check your apache logs or your webserver logs then.

Regards,
FAiZ
