### ISSUE TITLE
Stuck at processing

### ISSUE THREAD

**Issue by cavinneoh** [aifaiz/ipay88-woocommerce#3]
not progressing after redirected to page with ipay88 template. "Please wait while we redirect you to the payment site." message appears but stays there. 

Followed your steps and inserted correct page ID at ipay88 settings.

How do I make it work? Is it because of merchant ID and merchant code? Currently using 000000

**Comment by aifaiz** [comment]
you can uncomment the `#ipaySubmitForm` on the jQuery. the latest version already updated.
```
<script>
        $(document).ready(function(){
            $('#ipaysubmitForm').submit();
        });
        </script>
```
