### ISSUE TITLE
Page stuck

### ISSUE THREAD

**Issue by goenrohas** [aifaiz/ipay88-woocommerce#5]
Hi Faiz,

I've installed the latest version of this plugin, but my payment page still show this: 
"Please wait while we redirect you to the payment site." 
Message appears and stays there.

I've change the target url and currency to ipay88 Indonesia given url and to Indonesian currency. but the problem happen before i changed the testpay url and currency.

How do I make it work?

**Comment by aifaiz** [comment]
hi. try inspect element on that page and see if there is an error in the console. probably your jQuery or javascript are preventing the page to load properly

**Comment by goenrohas** [comment]
Hi Faiz,

Tq for your fast respond, i'll check the page.

**Comment by goenrohas** [comment]
Dear Faiz,

As far I just seen this unusual script in console.
<script type='text/javascript'> /*CDATA[ */var woocommerce_params = {....} */ </script>


Is that indicate that there is something wrong that make redirecting page to ipay88 stop?
If yes, what should i do?

**Comment by goenrohas** [comment]
and this redirecting script on aics-ipay-gateway file print as it is:

<script>
        jQuery(document).ready(function(){
            jQuery('#ipaysubmitForm').submit();
        });
        </script>

**Comment by aifaiz** [comment]
the best is to check if your plugins or themes had error in the console. debuging one by one is the only solution i could advise you for now as its not related to the plugin bug

**Comment by goenrohas** [comment]
Is it mean that the page not redirect to payment gateway site, because some error in wordpress theme or (another) wordpress plugin ?

**Comment by aifaiz** [comment]
i assume it is like that. because. when the page completed loading. it should run the code  `jQuery('#ipaysubmitForm').submit();`
and post the form the the ipay url

**Comment by aifaiz** [comment]
does your javascript console in the inspect element provide any error? try screenshot that error and post is here

**Comment by goenrohas** [comment]
Thank you Faiz,

Since i'm just newbie on this website thing. I will try to use another theme and plugin to see what happen.

Best Regards,
Goen

**Comment by aifaiz** [comment]
alright
