### ISSUE TITLE
Update for the form element name in admin panel

### ISSUE THREAD

**Issue by handyman90** [aifaiz/ipay88-woocommerce#6]
I am not sure if ipay88 change the name recently, but swapping the merchant code in merchant ID input form works.

Merchant ID to Merchant Code

Merchant Code to Merchant Key

**Comment by aifaiz** [comment]
hi, alright thanks for suggestion

**Comment by aifaiz** [comment]
i have pushed an update to the repo and the `wordpress` directory too. Thank you for your suggestion
