### ISSUE TITLE
Issue with IOS

### ISSUE THREAD

**Issue by TeckVe** [aifaiz/ipay88-woocommerce#7]
Hello Faiz,

Thank you for the wonderful plugin. It is really helpful to me.
However I'm having this issue whereby when I try to checkout using ios/android, it will just freeze on the Processing page. Do you have any idea?
Thank you.

**Comment by aifaiz** [comment]
Hi, sorry for the late reply. this plugin should checkout fine when using browser i think. could you screenshot for give more info about how ios `freeze` ?

**Comment by aifaiz** [comment]
Hi. i think your issue probably related to the #10 issue. try see if your javascript on the theme are working properly
