### ISSUE TITLE
Set as default

### ISSUE THREAD

**Issue by dutchuy72** [aifaiz/ipay88-woocommerce#8]
Not so much an issue as a question (or three):
1. When selecting the "Testing payment or live payment" checkbox, is the environment in testing mode or in live mode? How can I tell that I'm in testing mode, and what does testing mode do?
2. Is there a way to select this plugin to be the default (selected) option on the checkout page?
3. Where can I add icons and a description to the "ipay88 Payment Gateway" selector on the checkout page, similar to the default PayPal selector? (see image below)

Thanks for the plugin!

![image](https://user-images.githubusercontent.com/30192935/28237459-b462494e-6972-11e7-983c-9575d4bd4bad.png)

**Comment by aifaiz** [comment]
Hi, 

thank you for using my plugin.

1. When selecting the "Testing/Live" checkbox. it is "testing" when `checked` and "Live" when `unchecked`.
2. I think as a plugin developed we are not able to gain control over the default `woocommerce` gateway as it was controlled by woocommerce `settings` page.
3. Currently U did not provide any options for adding `icons` and `descriptions` to the seletcor. Sorry for the inconvenience. But I will take not of it for improvement.

You are welcome! and thank you for the feedback!

Reagrds,
FAiZ
